[supabase]
url = "https://koguhddaikzhyaexfoop.supabase.co"
key = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImtvZ3VoZGRhaWt6aHlhZXhmb29wIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Mzk5MDgyNTIsImV4cCI6MjA1NTQ4NDI1Mn0.vKTHGfdUhx5FDC7di7rkTYw3bAvMs2tmYAfastOERwQ"
